// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop {
    
    
    public partial class GendarmeConfig {
        
        private Gtk.Table table1;
        
        private Gtk.Button btnOpen;
        
        private Gtk.Entry edtPath;
        
        private Gtk.Entry edtSet;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget MonoDevelop.GendarmeConfig
            Stetic.BinContainer.Attach(this);
            this.Events = ((Gdk.EventMask)(0));
            this.Name = "MonoDevelop.GendarmeConfig";
            // Container child MonoDevelop.GendarmeConfig.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table1.Events = ((Gdk.EventMask)(0));
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.btnOpen = new Gtk.Button();
            this.btnOpen.CanFocus = true;
            this.btnOpen.Events = ((Gdk.EventMask)(0));
            this.btnOpen.Name = "btnOpen";
            this.btnOpen.UseStock = true;
            this.btnOpen.UseUnderline = true;
            this.btnOpen.Label = "gtk-open";
            this.table1.Add(this.btnOpen);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.btnOpen]));
            w1.LeftAttach = ((uint)(2));
            w1.RightAttach = ((uint)(3));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.edtPath = new Gtk.Entry();
            this.edtPath.CanFocus = true;
            this.edtPath.Events = ((Gdk.EventMask)(0));
            this.edtPath.Name = "edtPath";
            this.edtPath.IsEditable = true;
            this.edtPath.InvisibleChar = '●';
            this.table1.Add(this.edtPath);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.edtPath]));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.edtSet = new Gtk.Entry();
            this.edtSet.CanFocus = true;
            this.edtSet.Events = ((Gdk.EventMask)(0));
            this.edtSet.Name = "edtSet";
            this.edtSet.IsEditable = true;
            this.edtSet.InvisibleChar = '●';
            this.table1.Add(this.edtSet);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.edtSet]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Events = ((Gdk.EventMask)(0));
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Rules file:");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Events = ((Gdk.EventMask)(0));
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Rule set:");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.btnOpen.Clicked += new System.EventHandler(this.OnBtnOpenClicked);
        }
    }
}
