// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop {
    
    
    public partial class GendarmeDisplay {
        
        private Gtk.VBox vbox3;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView vView;
        
        private Gtk.Statusbar statusbar1;
        
        private Gtk.Label label1;
        
        private Gtk.ProgressBar progressbar;
        
        private Gtk.Label label4;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label lblVio;
        
        private Gtk.Label label6;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label lblRules;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget MonoDevelop.GendarmeDisplay
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.GendarmeDisplay";
            // Container child MonoDevelop.GendarmeDisplay.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.VscrollbarPolicy = ((Gtk.PolicyType)(1));
            this.scrolledwindow1.HscrollbarPolicy = ((Gtk.PolicyType)(1));
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.vView = new Gtk.TreeView();
            this.vView.CanFocus = true;
            this.vView.Name = "vView";
            this.vView.HeadersVisible = false;
            this.scrolledwindow1.Add(this.vView);
            this.vbox3.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.scrolledwindow1]));
            w2.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.statusbar1 = new Gtk.Statusbar();
            this.statusbar1.Name = "statusbar1";
            this.statusbar1.Spacing = 17;
            this.statusbar1.BorderWidth = ((uint)(1));
            // Container child statusbar1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<b>Progress</b>");
            this.label1.UseMarkup = true;
            this.statusbar1.Add(this.label1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.statusbar1[this.label1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child statusbar1.Gtk.Box+BoxChild
            this.progressbar = new Gtk.ProgressBar();
            this.progressbar.Name = "progressbar";
            this.statusbar1.Add(this.progressbar);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.statusbar1[this.progressbar]));
            w4.Position = 2;
            // Container child statusbar1.Gtk.Box+BoxChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("<b>Violations found:</b>");
            this.label4.UseMarkup = true;
            this.statusbar1.Add(this.label4);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.statusbar1[this.label4]));
            w5.Position = 3;
            w5.Expand = false;
            w5.Fill = false;
            // Container child statusbar1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.lblVio = new Gtk.Label();
            this.lblVio.Name = "lblVio";
            this.lblVio.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.hbox2.Add(this.lblVio);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.lblVio]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("<b>Rules checked:</b>");
            this.label6.UseMarkup = true;
            this.hbox2.Add(this.label6);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.label6]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.statusbar1.Add(this.hbox2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.statusbar1[this.hbox2]));
            w8.Position = 4;
            w8.Expand = false;
            w8.Fill = false;
            // Container child statusbar1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.lblRules = new Gtk.Label();
            this.lblRules.Name = "lblRules";
            this.lblRules.LabelProp = Mono.Unix.Catalog.GetString("0");
            this.hbox3.Add(this.lblRules);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox3[this.lblRules]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            this.statusbar1.Add(this.hbox3);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.statusbar1[this.hbox3]));
            w10.Position = 5;
            this.vbox3.Add(this.statusbar1);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox3[this.statusbar1]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.vView.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnVViewButtonPressEvent);
            this.vView.RowExpanded += new Gtk.RowExpandedHandler(this.OnVViewRowExpanded);
            this.vView.RowActivated += new Gtk.RowActivatedHandler(this.OnVViewRowActivated);
        }
    }
}
